== AeroGear Services Core SDK

Core SDK provides numbers of helpers for individual SDK's 
Core can be also used 

See link:../getting-started.adoc[SDK architecture] for more details.

=== Core Services Api

Core SDK supports currently following areas

1. Configuration parser
1. Network library 
1. Default logger shared between SDK.

=== Logger

Logger is initialized automatically and available as static member of AgsCore.
Example:

[source,swift]
----
 AgsCore.logger.debug("Message")
----

End users can change or disable logger in top level application by providing empty implementation.

[source,swift]
----
 AgsCore.setLogger(AgsLoggable())
----
 
=== Network library

Network library offers common wrapper for making any networking requests.
Wrapper by default works with popular AlamoFire Swift library.

==== Usage

[source,swift]
----
 coreInstance.getHttp().get(uri, { (response, error) -> Void in
        if let error = error {
            AgsCore.logger.error("An error has occurred during read! \(error)")
            return
        }
        // Unwrap optional
        if let response = response as? [String: Any] {
            // Operate on response Dictionary
            print(response)
        }
    })
----

==== Working with structures

Network interface requires payload to be dictionary.
Users can still work with structures and transform them back to dictionary.
Any structure that implements `Codable` protocol can be transformed to Dictionary thanks to convenience method:
`structureInstance.adaptToDictionary()`