platform :ios, '9.0'

target 'AeroGearSdkExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!


  # pod 'AGCore', :path => '../modules/core'

  # Pods for AeroGearSdkExample

  target 'AeroGearSdkExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
