platform :ios, '9.0'

target 'AeroGearSdkExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AeroGearSdkExample
  # Should contain each individual mobile services
  pod 'AGSCore', :path => '../modules/core'
  pod 'AGSAuth', :path => '../modules/auth'

  target 'AeroGearSdkExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
