osx_image: xcode9.2
language: objective-c
cache:
  - bundler
  - cocoapods

rvm: 2.3.1
before_install:
  - bundle install
  - gem install xcpretty
  - bundle exec pod install --project-directory=example --repo-update
  - echo "$TRAVIS_COMMIT_RANGE"
  - echo "$TRAVIS_PULL_REQUEST"
script:
  - ./scripts/testing.sh
branches:
  only:
    - master
