= AeroGear Services Auth SDK

Mobile authentication SDK based on link:http://www.keycloak.org/[Keycloak] using link:http://openid.net/connect/[OpenID Connect].

== Usage

To use the Auth SDK you'll first need to:

* Have a Keycloak instance.
* Import the Core module. See link:./core/README.adoc[the Core documentation].
* A configuration file added to the app directory. See the <<Configuration File>> section.

=== Adding Dependency

Add dependency to your Podfile:

```
pod 'AGSAuth'
```

=== Configuration File

A `mobile-services.json` file must exist in the app directory. It should specify configuration
for Keycloak. This configuration can be generated by the link:https://github.com/aerogear/mobile-cli[AeroGear Mobile CLI].

For an example of Keycloak configuration see the example apps link:../../example/AeroGearSdkExample/mobile-services.json[mobile-services.json].

The Auth SDK will use this configuration to communicate with Keycloak.

=== Initializing the SDK
The Auth SDK can be initialised with configuration options. The redirect URL should match the App's Bundle Identifier.

[source,swift]
----
let authenticationConfig = AuthenticationConfig(redirectURL: "org.aerogear.mobile.example:/callback")
try! AgsAuth.instance.configure(authConfig: authenticationConfig)
----

=== Retrieving the Current User
The current authenticated user can be retrieved using the `currentUser()` method.
This function can be be used to check whether to start the authentication flow or not if the user is not authenticated.

[source,swift]
----
do {
    guard let currentUser = try AgsAuth.instance.currentUser() else {
        // user not authenticated, start authentication flow
        return
    }
    // Get the users username
    var username = currentUser.userName
    // Get the users first name
    var firstName = currentUser.firstName
    // Get the users last name
    var lastName = currentUser.lastName
    // Get the users full name
    var fullName = currentUser.fullName
    // Get the users email address
    var emailAddress = currentUser.email
    // Get the users access token
    var accessToken = currentUser.accessToken
    // Get the users identity token
    var identityToken = currentUser.identityToken
} catch {
    fatalError("Error Retrieving User: \(error).")
}
----

=== Authenticating
[source,swift]
----
// start the authentication flow
try AgsAuth.instance.login(presentingViewController: self, onCompleted: onLoginComplete)

...

// handle the authentication result
func onLoginComplete(user: User?, err: Error?) {
    // login failed
    if let error = err {
        showSimpleAlert(title: "Login Error", message: "Error occurred during login flow \(error)")
        return
    }
    // login suceeded
    var currentUser = user
    ...
}
----

In your app's https://developer.apple.com/documentation/uikit/uiapplicationdelegate[AppDelegate], you will need to allow your application to handle the redirect.

[source,swift]
----
func application(_ app: UIApplication, open url: URL, options: [UIApplicationOpenURLOptionsKey: Any] = [:]) -> Bool {
    do {
        return try AgsAuth.instance.resumeAuth(url: url as URL)
    } catch AgsAuth.Errors.serviceNotConfigured {
        print("AeroGear auth service is not configured")
    } catch {
        fatalError("Unexpected error: \(error).")
    }
    return false
}
----

=== Retrieving a Users Roles


=== Logging Out


=== Single Sign-on
