== AeroGear Services Core SDK

The Core SDK provides a minimal set of helper functions which is used by the individual service SDKs. 

See the link:../service-guide.adoc[Service Contributor Guide] for an explanation of the SDK Architecture.

=== Core Services Api

The core SDK currently supports the following areas:

1. Configuration parser
2. Network library 
3. Default logger shared between SDK.
4. Metrics (documented in separate chapter)

=== Logger

The core SDK provides a logger. The logger is automatically initialized and available as a property of `AgsCore`.

[source,swift]
----
 AgsCore.logger.debug("Message")
----

End users can change or disable the logger in their applications by providing an empty implementation.

[source,swift]
----
 AgsCore.setLogger(AgsLoggable())
----
 
=== Network library

The network library offers a common wrapper for making networking requests.
By default, the wrapper uses the popular AlamoFire Swift library.

==== Usage

[source,swift]
----
 coreInstance.getHttp().get(uri, { (response, error) -> Void in
        if let error = error {
            AgsCore.logger.error("An error has occurred during read! \(error)")
            return
        }
        // Unwrap optional
        if let response = response as? [String: Any] {
            // Operate on response Dictionary
            print(response)
        }
    })
----

==== Working with structures

Network interface requires payload to be dictionary.
Users can still work with structures and transform them back to dictionary.
Any structure that implements `Codable` protocol can be transformed to Dictionary thanks to convenience method:
`structureInstance.adaptToDictionary()`
