== SDK Release Documentation

The release process results in new versions of the Core and associated SDKs being published on Cocoapods. The version numbers on all SDKs must always be the same.

For more info about cocoapods releases please visit:
https://guides.cocoapods.org/making/specs-and-specs-repo.html

=== How do Releases Work?

The release process takes place in CircleCI. CircleCI notices a new release being created and kicks off a special release workflow. The following steps take place:

* A standard build job runs, i.e. the code is built and tested.
* If the build is successful then a release job runs.
  ** The podspec files are validated to make sure all the version numbers match
  ** The Release tag is validated to make sure it matches the version numbers in the podspec files
  ** The Core SDK is released first
  ** The associated SDKs are released.

A small amount of preparation needs to take place before this process kicks off. Version numbers need to be updated accordingly using the scripts provided.

=== How to Prepare a Release

Ensure the git repo is clean and there are no outstanding changes. Then check out a new branch.

[source, bash]
--
git checkout -b release-x.y.z
--

Update the version number in the `VERSION` file at the root of the repository. The version number **must be in the format x.y.z.**

**From the root directory** run the `prep-release.sh` script.

[source, bash]
--
./scripts/prep-release.sh
--

Use `git status` to verify that the version numbers in the correct files have been updated.

[source, bash]
--
$ git status
On branch release-x.y.z
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   AGSAuth.podspec
        modified:   AGSCore.podspec
        modified:   AgsPush.podspec
        modified:   VERSION
        modified:   modules/core/data/AgsMetadata.swift
--

Commit and push these changes, then open a Pull Request to `master`.

[source, bash]
--
git commit -am 'release version x.y.z'
--

=== How to Release

Once your changes have been merged to master, you can continue and release to Cocoapods.

To kick off a release to Cocoapods, simply link:https://help.github.com/articles/creating-releases/[Create a Release] in Github. **You must use the exact `x.y.z` format** for the release tag or the release will fail.

This will kick off the automatic release process in CircleCI.