== AeroGear Service Developer Guide

Following guide describes architecture for IOS SDK and instructions for developing new AeroGear Services.

For instructions about using SDK in user applications please follow link:./getting-started.adoc[User Getting Started Guide]

image:./images/diagram.svg[diagram,450,450,role="right"]

=== SDK architecture

SDK aggregates individual services SDK into one single managable namespace. Services like AeroGear Sync, Push are build as separate SDK's that can be included into any existing or new IOS applications. SDK using cocoapods for dependency resolution and distribution. Each SDK contains separate `podspec` file. Specifications are tested in `./example` application that is also used for building and demo purposes. 

Each SDK always include separate core module located in `./modules/core`.
Core is responsible for parsing configuration, event logging and network communitcation. Both top level users and individual SDK components can interact with Core SDK api in order to avoid strict dependencies. 

Every SDK is fully independent from each other and interacts with Core interfaces. 

=== Folder structure

`./modules` - folder containing AeroGear services.  
Each service (cocoapods module) is represented by podspec file

`./example` - folder with example application used for testing etc.
Example application also contain

`./scripts` - scripts for development, build, releases etc.
See each script header for more information

`./docs` - documentation for SDK. Contains documentation for each service

`./AeroGearServices.podspec` - global pod specification that will be used for release purposes.
While each module will have their own pod specification 

`AeroGearServices.podspec` will aggregate all of them into single specification that 
can be used to release changes under single namespace `AeroGearServices/ServiceName`

=== Creating new service

Instruction bellow explains how to crete new IOS based SDK

1. Execute script that will create all required artifacts
+
[source,bash]
----
   ./scripts/generate-service.sh --name myservice
----
+
1. Review generated podspec file
+
[source,bash]
----
   open ./modules/myservice/myservice.podspec
----
+
1. Open generated file and write your SDK source code
+
[source,bash]
----
    open ./modules/myservice/myservice.swift
----
+
1. Write usage example in service documentation
+
[source,bash]
----
    open ./docs/myservice/README.adoc
----
+
1. Link module to example application Podfile
+
[source,ruby]
----
    pod 'myservice', :path => '../modules/myservice'
----
+
1. Install dependencies
+
[source,bash]
----
    cd ./example
    pod install
----
+
1. Write unit tests
+
[source,bash]
----
open ./example/AeroGearSdkExampleTests/myservice/MyserviceTests.swift
----

=== XCode development

SDK and example applications can be developed in XCode. 
To open xcode project Execute

----
open ./example/AeroGearSdkExample.xcworkspace
----

Example application source code is grouped in `AeroGearSdkExample` folder
SDK source code is grouped in `Pods` > `Development pods` folder

=== Troubleshooting 

==== XCode is missing files

When switching between branches XCode will not be able to recognize the changes.
This may be often seen as compilation errors when file is missing.

To fix this problem developer need to:

1. Close Xcode
2. Run `pod install`
3. Reopen project again

> Note: Please make sure that cocoapods contains latest index before running pod install